sudo: required
services:
    - docker

before_install:
    - docker build -t dimplejariwala/docker-react -f Dockerfile.dev . 

script:
    - docker run dimplejariwala/docker-react npm run test -- --coverage


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker-React"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-496820115691"
    bucket_path: 'Docker-React'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_key_id: 
      secure: "$AWS_SECRET_KEY"